### PR TITLE
put the logo on

### PR DESCRIPTION
**Pull request by edunham**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo.org/7)

### CODE REVIEW

**Comment by edunham** [comment]
or could a decision get made in  https://github.com/servo/servo/issues/3893 and use that logo instead?

**Comment by metajack** [comment]
I have someone working on a real logo from #3893, but it probably wont' be ready for several more weeks. Proceed with the doge for now :)

**Comment by mbrubeck** [comment]
I think this should wait until an official logo is chosen in #3893.  The doge logo is fine for developer builds and inside jokes, but for more prominent public use we should make sure we don't run afoul of the [Rust trademark policy](https://www.rust-lang.org/legal.html):

> Using the Rust trademarks within another trademark requires written permission from the Rust core team except as described above.

and the [Mozilla Trademark policy](https://www.mozilla.org/en-US/foundation/trademarks/policy/):

> There is one additional broad category of things you can't do with Mozilla's Marks. Produce modified versions of them.

Since both Servo and the Rust trademarks are owned by Mozilla, we potentially _could_ get permission to do this. But there's also a question of ownership of the doge image, and of whether it's a good idea to set an example that other Rust projects can't follow.

**Comment by larsbergstrom** [comment]
I'll send mail to the Rust core team.

I would prefer that we explicitly not look _too_ official, especially in our alpha releases. Before we start making Servo look like a real product, we should engage deeply with Firefox program management. There is a huge risk in devaluing the brand and confusing our userbase (plus annoying off the Firefox team!) if we push too hard too fast with Servo-as-product.

I've been through that experience before (on VS) and it was a PR nightmare plus a huge morale killer when our incubation project leaked and was mistaken by the press to be the Next Big Thing and devalued the imminent upcoming releases from the product org.

**Comment by edunham** [comment]
Would it be an acceptable compromise to use a doge meme without the Rust logo, such as this?

servodogememe

**Comment by Manishearth** [comment]
Such r, many +

**Comment by larsbergstrom** [comment]
The Rust core team has provided written approval of our Servo-doge-Rust logo usage.

**Comment by edunham** [comment]
@larsbergstrom Thank you for getting permission -- that logo usage also means that @bors-servo is in the clear. 

Your point about getting taken seriously by developers and the media before we're ready is compelling, though. I've pushed an even less polished-looking doge so that people would look even sillier for taking the site seriously.

**Comment by edunham** [comment]
In the meantime, an actual screenshot was PR'd. Merged it, since it carries useful information about Servo's ability to render things rather than a questionably copyright-infringing meme.

**Pull request closed without merging**
