### PR TITLE
Line wrap, remove redundancy, and remove 'performant'

### PR DESCRIPTION
**Pull request by edunham**
> 182 14:29:00 @jack edunham: larsberg: someone change performant to high-performance or i      will die inside

Can't have @metajack dying, inside or out!

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo.org/26)

### CODE REVIEW

**Comment by edunham** [comment]
Old phrasing: 

> Servo is a modern, performant browser engine designed to be appropriate for applications including embedded use. 

New phrasing: 

> ~~Servo is a modern, high-performance browser engine designed for applications including embedded use.~~
> 
> Servo is a modern, high-performance browser engine designed for both application and embedded use.

**Comment by metajack** [comment]
how about "design for both applications and embedding". with that or something similar r=me

**Comment by edunham** [comment]
I think it's correct to phrase "runs in userland" as "designed for application use"?

**Comment by edunham** [comment]
```
15:40:00 <@jack> edunham: feel free to correct my grammar if need be :)
```

Grammar corrected; merging r=jack.

**Pull request merged**
