### PR TITLE
Landing Page for Servo

### PR DESCRIPTION
**Pull request by lucywyman**
[Review on Reviewable](https://reviewable.io/reviews/servo/servo.org/4)

### CODE REVIEW

**Comment by lucywyman** [comment]
@edunham  Ok, I addressed:
1. Adding contributing information
2. Doge

Do you want the news section to just pull the most recent blog post? List the most recent three links from the blog?  I'm going to try the latter, but let me know if that's not what you were thinking!

I'll also try to have more flexbox ;)

**Comment by edunham** [comment]
@lucywyman Including the most recent blog post could be really neat! 

Could you link that prototype site that you mentioned on IRC from here? 

https://github.com/servo/servo/issues/8365

**Comment by edunham** [comment]
One tiny nitpick, which I don't think should block merge: In a small window, the headings at the top overlap rather than stacking. screenshot

Would it be possible to make them stack vertically when the screen is too small, or disappear behind a hamburger-menu button the way sites like https://viewsourceconf.org/ do on mobile?

**Comment by edunham** [comment]
Closing as discussed in https://github.com/servo/servo/issues/8365 -- please PR this awesome content into the current site!

**Pull request closed without merging**
