### PR TITLE
Make the capitalization consistent in titles

### PR DESCRIPTION
**Pull request by Coder206**
Modify the title tag to match the page title

---
This change is [Reviewable](https://reviewable.io/reviews/servo/servo.org/73)

### CODE REVIEW

**Comment by jdm** [comment]
I don't think capitalizing each word of the page title is an improvement.

**Comment by Coder206** [comment]
When viewing the website, it feels disconnected to me as the use of capitalization is inconsistent.

See:
screenshot

**Comment by Coder206** [comment]
@jdm What are your thoughts on changing the title tag to "Homepage - Servo"?

**Comment by jdm** [comment]
I'm inclined to leave the title as it is.

**Pull request closed without merging**
