### PR TITLE
Add a static version of browser.html's about:newtab for easy testing

### PR DESCRIPTION
**Pull request by tschneidereit**
r? @metajack 

The list of included sites isn't final by any means, of course, but it's what we have in browser.html right now.

---

This change is [Reviewable](https://reviewable.io/reviews/servo/servo.org/23)

### CODE REVIEW

**Comment by Manishearth** [comment]
Are we allowed to use these images in this repo?

**Comment by tschneidereit** [comment]
> Are we allowed to use these images in this repo?

We do have them in the browser.html repo, so I'm assuming that has been
checked.

**Comment by Ms2ger** [comment]
That seems implausible... @metajack?

**Comment by tschneidereit** [comment]
> That seems implausible... @metajack https://github.com/metajack?
> 
> I tend to agree. Perhaps we should just not land this for now.

**Comment by metajack** [comment]
I think this is likely to be an allowed use, but it is easy to check. For example: https://www.youtube.com/yt/brand/using-logo.html lists the rules for YouTube logo usage.

This particular page contains more icons than we will need, so we only need to check the ones that work well in Servo.

**Comment by metajack** [comment]
As this is no worse that what we're already doing, I'm going to land this so I can do the surgery on it to get it to have the correct tiles.

**Pull request merged**
