### PR TITLE
Mention that we work on windows now. And 32 bit.

### PR DESCRIPTION
**Pull request by Manishearth**
Not sure if we work on 32 bit windows though; perhaps I should clarify it as "64 bit Windows"?

r? @larsbergstrom

[Review on Reviewable](https://reviewable.io/reviews/servo/servo.org/17)

### CODE REVIEW

**Comment by jdm** [comment]
I'd prefer to not advertise this until we have CI for Windows. I'm pretty sure it doesn't build since the webrender integration merged.

**Comment by KiChjang** [comment]
Don't we already have AppVeyor taking care of the windows build for us?

**Comment by Manishearth** [comment]
Not yet.

**Pull request merged**
